# Generated by Django 5.1.5 on 2025-02-17 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_realizacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('hotel', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('imagen_destacada', models.URLField(blank=True, null=True)),
                ('actividades', models.ManyToManyField(related_name='viajes', to='api.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
