# Generated by Django 5.0.3 on 2025-04-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actividad_fecha_realizacion_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('imagen', models.URLField()),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='api.viaje')),
            ],
        ),
    ]
