# Generated by Django 5.0.3 on 2025-04-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_bio_customuser_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compartido', to='api.viaje')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='LikeViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje_compartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.viajecompartido')),
            ],
            options={
                'unique_together': {('usuario', 'viaje_compartido')},
            },
        ),
    ]
