# Generated by Django 5.0.3 on 2025-05-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_viajecompartido_likeviaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='viaje',
        ),
        migrations.AddField(
            model_name='actividad',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EstanciaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estancias', to='api.viaje')),
            ],
        ),
    ]
