# Generated by Django 5.0.3 on 2025-05-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_actividad_ubicacion_remove_hotel_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='ciudad',
            new_name='direccion',
        ),
    ]
