# Generated by Django 5.0.3 on 2025-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_ciudad_hotel_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
