# Generated by Django 5.0.3 on 2025-05-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_actividad_google_place_id_hotel_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='url_imagen',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
