# Generated by Django 5.0.3 on 2025-05-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_ciudad_actividad_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='direccion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='url_imagen',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=2000),
        ),
    ]
