# Generated by Django 5.0.3 on 2025-05-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_actividad_direccion_alter_actividad_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('cantidad', models.FloatField()),
                ('categoria', models.CharField(choices=[('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Alojamiento', 'Alojamiento'), ('Ocio', 'Ocio'), ('Compras', 'Compras'), ('Otros', 'Otros')], max_length=50)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='api.viaje')),
            ],
        ),
    ]
