# Generated by Django 5.0.3 on 2025-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada')], default='pendiente', max_length=10),
        ),
    ]
