# Generated by Django 5.0.3 on 2025-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_relacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_google',
            field=models.BooleanField(default=False),
        ),
    ]
